name: Mandrel-Quarkus tests

on: 
  workflow_call:    
    inputs:
      issue-number:
        type: string
        description: 'The issue number to report results to'
        default: "null"
  workflow_dispatch:
    inputs:
      issue-number:
        type: string
        description: 'The issue number to report results to'
        default: "null"

jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - run: python --version
      - run: |
          echo "MY_INPUT=${{ inputs.issue-number }}" >> $GITHUB_ENV

  pass-fail:
    name: Pass Fail ${{ matrix.command }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command: ["true", "false"]
    steps:
      - run: ${{ matrix.command }}

  pass-fail-report:
    name: Report
    if: always()
    runs-on: ubuntu-latest
    needs:
      - pass-fail
    steps:
      - run: echo ${{ needs.pass-fail.result }}
