name: Triggered Workflow

on:
  workflow_run:
    workflows: ["Mandrel-Quarkus tests"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Triggering Workflow Run ID
        shell: bash
        run: |
            echo "Triggering Workflow Run ID: ${{ github.event.workflow_run.id }}"
      - name: Get Triggering Workflow Run context
        shell: bash
        run: |
            echo "Triggering Workflow Run Context: ${{ toJson(github.event.workflow_run) }}"